// Code generated by generator, DO NOT EDIT.
package demodef

import (
	"encoding/json"
	attr "gitlab.gamesword.com/nut/entitygen/attr"
	bson "go.mongodb.org/mongo-driver/bson"
)

var Vector3Meta *attr.Meta

func init() {
	Vector3Meta = &attr.Meta{}

	Vector3Meta.DefAttr("x", attr.Float32, attr.AfBase, true)
	Vector3Meta.DefAttr("y", attr.Float32, attr.AfBase, true)
	Vector3Meta.DefAttr("z", attr.Float32, attr.AfBase, true)
}

type Vector3 attr.StrMap

func EmptyVector3() *Vector3 {
	return NewVector3(0, 0, 0)
}
func NewVector3(x float32, y float32, z float32) *Vector3 {
	m := (*Vector3)(attr.NewStrMap(nil))
	m.SetX(x)
	m.SetY(y)
	m.SetZ(z)
	m.ClearChangeKey()
	return m
}
func (a *Vector3) GetX() float32 {
	val := (*attr.StrMap)(a).Float32("x")
	return val
}
func (a *Vector3) SetX(x float32) {
	(*attr.StrMap)(a).Set("x", x)
}

func (a *Vector3) GetY() float32 {
	val := (*attr.StrMap)(a).Float32("y")
	return val
}
func (a *Vector3) SetY(y float32) {
	(*attr.StrMap)(a).Set("y", y)
}

func (a *Vector3) GetZ() float32 {
	val := (*attr.StrMap)(a).Float32("z")
	return val
}
func (a *Vector3) SetZ(z float32) {
	(*attr.StrMap)(a).Set("z", z)
}

func (a *Vector3) HasChange() bool {
	return (*attr.StrMap)(a).HasChange()
}
func (a *Vector3) ChangeKey() map[string]struct{} {
	return (*attr.StrMap)(a).ChangeKey()
}
func (a *Vector3) ClearChangeKey() {
	(*attr.StrMap)(a).ClearChangeKey()
}
func (a *Vector3) setParent(k string, parent attr.Field) {
	(*attr.StrMap)(a).SetParent(k, parent)
}
func (a *Vector3) ForEach(fn func(k string, v interface{}) bool) {
	(*attr.StrMap)(a).ForEach(fn)
}
func (a *Vector3) Equal(other *Vector3) bool {
	return (*attr.StrMap)(a).Equal((*attr.StrMap)(other))
}
func (a *Vector3) Undertype() interface{} {
	return (*attr.StrMap)(a)
}
func (a *Vector3) Data() map[string]interface{} {
	dd := map[string]interface{}{}
	a.ForEach(func(k string, v interface{}) bool {
		dd[k] = v
		return true
	})
	return dd
}
func (a *Vector3) MarshalJSON() ([]byte, error) {
	return json.Marshal((*attr.StrMap)(a).ToMap())
}
func (a *Vector3) UnmarshalJSON(b []byte) error {
	mm, err := Vector3Meta.UnmarshalJson(b)
	if err != nil {
		return err
	}
	(*attr.StrMap)(a).SetData(mm)
	(*attr.StrMap)(a).ForEach(func(k string, v interface{}) bool {
		if k != "id" && !Vector3Meta.GetDef(k).IsPrimary() {
			v.(IField).setParent(k, (*attr.StrMap)(a))
		}
		return true
	})
	return nil
}
func (a *Vector3) MarshalBSON() ([]byte, error) {
	return bson.Marshal((*attr.StrMap)(a).ToMap())
}
func (a *Vector3) UnmarshalBSON(b []byte) error {
	mm, err := Vector3Meta.UnmarshalBson(b)
	if err != nil {
		return err
	}
	(*attr.StrMap)(a).SetData(mm)
	(*attr.StrMap)(a).ForEach(func(k string, v interface{}) bool {
		if k != "id" && !Vector3Meta.GetDef(k).IsPrimary() {
			v.(IField).setParent(k, (*attr.StrMap)(a))
		}
		return true
	})
	return nil
}
