// Code generated by generator, DO NOT EDIT.
package entitydef

import (
	"encoding/json"
	"fmt"
	attr "gitlab.gamesword.com/nut/entitygen/attr"
	bson "go.mongodb.org/mongo-driver/bson"
)

type DeskDefSlice attr.Slice

func EmptyDeskDefSlice() *DeskDefSlice {
	return NewDeskDefSlice(nil)
}
func NewDeskDefSlice(items []*DeskDef) *DeskDefSlice {
	var convertData []interface{} = []interface{}{}
	for _, v := range items {
		convertData = append(convertData, v)
	}
	return (*DeskDefSlice)(attr.NewSlice(convertData))
}
func (a *DeskDefSlice) Set(idx int, item *DeskDef) {
	item.setParent(fmt.Sprintf("ik%d", idx), (*attr.Slice)(a))
	(*attr.Slice)(a).Set(idx, item)
}
func (a *DeskDefSlice) Add(item *DeskDef) {
	idx := a.Count()
	item.setParent(fmt.Sprintf("ik%d", idx), (*attr.Slice)(a))
	(*attr.Slice)(a).Add(item)
}
func (a *DeskDefSlice) At(idx int) *DeskDef {
	val := (*attr.Slice)(a).Value(idx)
	if val == nil {
		return nil
	}
	return val.(*DeskDef)
}
func (a *DeskDefSlice) DelAt(idx int) bool {
	return (*attr.Slice)(a).DeleteAt(idx)
}
func (a *DeskDefSlice) Count() int {
	return (*attr.Slice)(a).Len()
}
func (a *DeskDefSlice) setParent(k string, parent attr.Field) {
	(*attr.Slice)(a).SetParent(k, parent)
}
func (a *DeskDefSlice) ForEach(fn func(k int, v *DeskDef) bool) {
	(*attr.Slice)(a).ForEach(func(k int, v interface{}) bool {
		return fn(k, v.(*DeskDef))
	})
}
func (a *DeskDefSlice) Equal(other *DeskDefSlice) bool {
	return (*attr.Slice)(a).Equal((*attr.Slice)(other))
}
func (a *DeskDefSlice) Undertype() interface{} {
	return (*attr.Slice)(a)
}
func (a *DeskDefSlice) data() []*DeskDef {
	dd := []*DeskDef{}
	a.ForEach(func(idx int, v *DeskDef) bool {
		dd = append(dd, v)
		return true
	})
	return dd
}
func (a *DeskDefSlice) MarshalJSON() ([]byte, error) {
	return json.Marshal(a.data())
}
func (a *DeskDefSlice) UnmarshalJSON(b []byte) error {
	dd := []*DeskDef{}
	err := json.Unmarshal(b, &dd)
	if err != nil {
		return err
	}
	convertData := []interface{}{}
	for k, v := range dd {
		v.setParent(fmt.Sprintf("ik%d", k), (*attr.Slice)(a))
		convertData = append(convertData, v)
	}
	(*attr.Slice)(a).SetData(convertData)
	return nil
}
func (a *DeskDefSlice) MarshalBSON() ([]byte, error) {
	return bson.Marshal(map[string][]*DeskDef{
		"d": a.data(),
	})
}
func (a *DeskDefSlice) UnmarshalBSON(b []byte) error {
	dd := map[string][]*DeskDef{}
	err := bson.Unmarshal(b, &dd)
	if err != nil {
		return err
	}
	convertData := []interface{}{}
	for k, v := range dd["d"] {
		v.setParent(fmt.Sprintf("ik%d", k), (*attr.Slice)(a))
		convertData = append(convertData, v)
	}
	(*attr.Slice)(a).SetData(convertData)
	return nil
}
