// Code generated by generator, DO NOT EDIT.
package entitydef

import (
	"encoding/json"
	"fmt"
	attr "gitlab.gamesword.com/nut/entitygen/attr"
	bson "go.mongodb.org/mongo-driver/bson"
)

type KVInt32DeskDef attr.Int32Map

func EmptyKVInt32DeskDef() *KVInt32DeskDef {
	return NewKVInt32DeskDef(nil)
}
func NewKVInt32DeskDef(data map[int32]*DeskDef) *KVInt32DeskDef {
	var convertData map[int32]interface{} = map[int32]interface{}{}
	for k, v := range data {
		convertData[k] = v
	}
	return (*KVInt32DeskDef)(attr.NewInt32Map(convertData))
}
func (a *KVInt32DeskDef) Set(k int32, v *DeskDef) {
	v.setParent(fmt.Sprintf("mk%d", k), (*attr.Int32Map)(a))
	(*attr.Int32Map)(a).Set(k, v)
}
func (a *KVInt32DeskDef) Get(k int32) *DeskDef {
	return (*attr.Int32Map)(a).Value(k).(*DeskDef)
}
func (a *KVInt32DeskDef) Delete(k int32) bool {
	return (*attr.Int32Map)(a).Delete(k)
}
func (a *KVInt32DeskDef) setParent(k string, parent attr.Field) {
	(*attr.Int32Map)(a).SetParent(k, parent)
}
func (a *KVInt32DeskDef) ForEach(fn func(k int32, v *DeskDef) bool) {
	(*attr.Int32Map)(a).ForEach(func(k int32, v interface{}) bool {
		return fn(k, v.(*DeskDef))
	})
}
func (a *KVInt32DeskDef) Equal(other *KVInt32DeskDef) bool {
	return (*attr.Int32Map)(a).Equal((*attr.Int32Map)(other))
}
func (a *KVInt32DeskDef) data() map[int32]*DeskDef {
	dd := map[int32]*DeskDef{}
	a.ForEach(func(k int32, v *DeskDef) bool {
		dd[k] = v
		return true
	})
	return dd
}
func (a *KVInt32DeskDef) MarshalJSON() ([]byte, error) {
	return json.Marshal((*attr.Int32Map)(a).ToMap())
}
func (a *KVInt32DeskDef) UnmarshalJSON(b []byte) error {
	dd := map[int32]*DeskDef{}
	err := json.Unmarshal(b, &dd)
	if err != nil {
		return err
	}
	convertData := map[int32]interface{}{}
	for k, v := range dd {
		v.setParent(fmt.Sprintf("mk%d", k), (*attr.Int32Map)(a))
		convertData[k] = v
	}
	(*attr.Int32Map)(a).SetData(convertData)
	return nil
}
func (a *KVInt32DeskDef) MarshalBSON() ([]byte, error) {
	return bson.Marshal((*attr.Int32Map)(a).ToMap())
}
func (a *KVInt32DeskDef) UnmarshalBSON(b []byte) error {
	dd := map[int32]*DeskDef{}
	err := bson.Unmarshal(b, &dd)
	if err != nil {
		return err
	}
	convertData := map[int32]interface{}{}
	for k, v := range dd {
		v.setParent(fmt.Sprintf("mk%d", k), (*attr.Int32Map)(a))
		convertData[k] = v
	}
	(*attr.Int32Map)(a).SetData(convertData)
	return nil
}
