// Code generated by generator, DO NOT EDIT.
package entitydef

import attr "entitygen/attr"

type KVStrInt32 attr.StrMap

func EmptyKVStrInt32() *KVStrInt32 {
	return NewKVStrInt32(nil)
}
func NewKVStrInt32(data map[string]int32) *KVStrInt32 {
	var convertData map[string]interface{} = map[string]interface{}{}
	for k, v := range data {
		convertData[k] = v
	}
	return (*KVStrInt32)(attr.NewStrMap(convertData))
}
