// Code generated by generator, DO NOT EDIT.
package entitydef

import attr "entitygen/attr"

type KVInt32DeskDef attr.Int32Map

func EmptyKVInt32DeskDef() *KVInt32DeskDef {
	return NewKVInt32DeskDef(nil)
}
func NewKVInt32DeskDef(data map[int32]*DeskDef) *KVInt32DeskDef {
	var convertData map[int32]interface{} = map[int32]interface{}{}
	for k, v := range data {
		convertData[k] = v
	}
	return (*KVInt32DeskDef)(attr.NewInt32Map(convertData))
}
func (a *KVInt32DeskDef) Set(k int32, v *DeskDef) {
	(*attr.Int32Map)(a).Set(k, v)
}
func (a *KVInt32DeskDef) Get(k int32) *DeskDef {
	return (*attr.Int32Map)(a).Value(k).(*DeskDef)
}
func (a *KVInt32DeskDef) Delete(k int32) bool {
	return (*attr.Int32Map)(a).Delete(k)
}
func (a *KVInt32DeskDef) setParent(k string, parent attr.Field) {
	(*attr.Int32Map)(a).SetParent(k, parent)
}
func (a *KVInt32DeskDef) ForEach(fn func(k int32, v *DeskDef) bool) {
	(*attr.Int32Map)(a).ForEach(func(k int32, v interface{}) bool {
		return fn(k, v.(*DeskDef))
	})
}
func (a *KVInt32DeskDef) Equal(other *KVInt32DeskDef) bool {
	return (*attr.Int32Map)(a).Equal((*attr.Int32Map)(other))
}
func (a *KVInt32DeskDef) data() map[int32]*DeskDef {
	dd := map[int32]*DeskDef{}
	a.ForEach(func(k int32, v *DeskDef) bool {
		dd[k] = v
		return true
	})
	return dd
}
