// Code generated by generator, DO NOT EDIT.
package entitydef

import attr "entitygen/attr"

type KVStrStr attr.StrMap

func EmptyKVStrStr() *KVStrStr {
	return NewKVStrStr(nil)
}
func NewKVStrStr(data map[string]string) *KVStrStr {
	var convertData map[string]interface{} = map[string]interface{}{}
	for k, v := range data {
		convertData[k] = v
	}
	return (*KVStrStr)(attr.NewStrMap(convertData))
}
