// Code generated by generator, DO NOT EDIT.
package entitydef

import attr "entitygen/attr"

type DeskXXXDef attr.StrMap

func (a *DeskXXXDef) GetWidth() int32 {
	return (*attr.StrMap)(a).Int32("width")
}
func (a *DeskXXXDef) SetWidth(width int32) {
	(*attr.StrMap)(a).Set("width", width)
}

func (a *DeskXXXDef) GetHeight() int32 {
	return (*attr.StrMap)(a).Int32("height")
}
func (a *DeskXXXDef) SetHeight(height int32) {
	(*attr.StrMap)(a).Set("height", height)
}

func (a *DeskXXXDef) GetName() string {
	return (*attr.StrMap)(a).Str("name")
}
func (a *DeskXXXDef) SetName(name string) {
	(*attr.StrMap)(a).Set("name", name)
}

func (a *DeskXXXDef) HasChange() bool {
	return (*attr.StrMap)(a).HasChange()
}
func (a *DeskXXXDef) ChangeKey() map[string]struct{} {
	return (*attr.StrMap)(a).ChangeKey()
}
func (a *DeskXXXDef) ClearChangeKey() {
	(*attr.StrMap)(a).ClearChangeKey()
}
