// Code generated by generator, DO NOT EDIT.
package entitydef

import (
	"encoding/json"
	attr "entitygen/attr"
)

var deskAttrDef *attr.Def

func init() {
	deskAttrDef = &attr.Def{}

	deskAttrDef.DefAttr("width", attr.Int32, attr.AfCell, true)
	deskAttrDef.DefAttr("height", attr.Int32, attr.AfCell, true)
	deskAttrDef.DefAttr("name", attr.String, attr.AfCell, true)
	deskAttrDef.DefAttr("csv_id", attr.Int32, attr.AfCell, true)
}

type DeskDef attr.StrMap

func (a *DeskDef) GetWidth() int32 {
	return (*attr.StrMap)(a).Int32("width")
}
func (a *DeskDef) SetWidth(width int32) {
	(*attr.StrMap)(a).Set("width", width)
}

func (a *DeskDef) GetHeight() int32 {
	return (*attr.StrMap)(a).Int32("height")
}
func (a *DeskDef) SetHeight(height int32) {
	(*attr.StrMap)(a).Set("height", height)
}

func (a *DeskDef) GetName() string {
	return (*attr.StrMap)(a).Str("name")
}
func (a *DeskDef) SetName(name string) {
	(*attr.StrMap)(a).Set("name", name)
}

func (a *DeskDef) GetCsvID() int32 {
	return (*attr.StrMap)(a).Int32("csv_id")
}
func (a *DeskDef) SetCsvID(csv_id int32) {
	(*attr.StrMap)(a).Set("csv_id", csv_id)
}

func (a *DeskDef) HasChange() bool {
	return (*attr.StrMap)(a).HasChange()
}
func (a *DeskDef) ChangeKey() map[string]struct{} {
	return (*attr.StrMap)(a).ChangeKey()
}
func (a *DeskDef) ClearChangeKey() {
	(*attr.StrMap)(a).ClearChangeKey()
}
func (a *DeskDef) setParent(k string, parent attr.Field) {
	(*attr.StrMap)(a).SetParent(k, parent)
}
func (a *DeskDef) ForEach(fn func(s string, v interface{}) bool) {
	(*attr.StrMap)(a).ForEach(fn)
}
func (a *DeskDef) MarshalJSON() ([]byte, error) {
	return json.Marshal((*attr.StrMap)(a).ToMap())
}
