// Code generated by generator, DO NOT EDIT.
package entitydef

import (
	"encoding/json"
	attr "gitlab.gamesword.com/nut/entitygen/attr"
	bson "go.mongodb.org/mongo-driver/bson"
)

var roomMeta *attr.Meta

func init() {
	roomMeta = &attr.Meta{}

	roomMeta.DefAttr("csv_pos", attr.Int32, attr.AfCell, true)
	roomMeta.DefAttr("build_id", attr.String, attr.AfCell, true)
	roomMeta.DefAttr("extends", &KVInt32Int32{}, attr.AfCell, true)
	roomMeta.DefAttr("extends1", &KVInt32Str{}, attr.AfCell, true)
	roomMeta.DefAttr("extends2", &KVStrInt32{}, attr.AfCell, true)
	roomMeta.DefAttr("extends3", &KVStrStr{}, attr.AfCell, true)
	roomMeta.DefAttr("desk888", &DeskDef{}, attr.AfCell, true)
	roomMeta.DefAttr("desks999", &KVInt32DeskDef{}, attr.AfCell, true)
	roomMeta.DefAttr("desks321", &KVStrDeskDef{}, attr.AfCell, true)
	roomMeta.DefAttr("desks", &DeskDefSlice{}, attr.AfCell, true)
	roomMeta.DefAttr("int8ss", &Int8Slice{}, attr.AfCell, true)
}

type RoomDef attr.StrMap

func EmptyRoomDef() *RoomDef {
	return NewRoomDef(0, "", EmptyKVInt32Int32(), EmptyKVInt32Str(), EmptyKVStrInt32(), EmptyKVStrStr(), EmptyDeskDef(), EmptyKVInt32DeskDef(), EmptyKVStrDeskDef(), EmptyDeskDefSlice(), EmptyInt8Slice())
}
func NewRoomDef(csv_pos int32, build_id string, extends *KVInt32Int32, extends1 *KVInt32Str, extends2 *KVStrInt32, extends3 *KVStrStr, desk888 *DeskDef, desks999 *KVInt32DeskDef, desks321 *KVStrDeskDef, desks *DeskDefSlice, int8ss *Int8Slice) *RoomDef {
	m := (*RoomDef)(attr.NewStrMap(nil))
	m.SetCsvPos(csv_pos)
	m.SetBuildID(build_id)
	m.SetExtends(extends)
	m.SetExtends1(extends1)
	m.SetExtends2(extends2)
	m.SetExtends3(extends3)
	m.SetDesk111(desk888)
	m.SetDesks222(desks999)
	m.SetDesks333(desks321)
	m.SetDesksArr(desks)
	m.SetInt8ss(int8ss)
	m.ClearChangeKey()
	return m
}
func (a *RoomDef) GetCsvPos() int32 {
	return (*attr.StrMap)(a).Int32("csv_pos")
}
func (a *RoomDef) SetCsvPos(csv_pos int32) {
	(*attr.StrMap)(a).Set("csv_pos", csv_pos)
}

func (a *RoomDef) GetBuildID() string {
	return (*attr.StrMap)(a).Str("build_id")
}
func (a *RoomDef) SetBuildID(build_id string) {
	(*attr.StrMap)(a).Set("build_id", build_id)
}

func (a *RoomDef) GetExtends() *KVInt32Int32 {
	return (*attr.StrMap)(a).Value("extends").(*KVInt32Int32)
}
func (a *RoomDef) SetExtends(extends *KVInt32Int32) {
	extends.setParent("extends", (*attr.StrMap)(a))
	(*attr.StrMap)(a).Set("extends", extends)
}

func (a *RoomDef) GetExtends1() *KVInt32Str {
	return (*attr.StrMap)(a).Value("extends1").(*KVInt32Str)
}
func (a *RoomDef) SetExtends1(extends1 *KVInt32Str) {
	extends1.setParent("extends1", (*attr.StrMap)(a))
	(*attr.StrMap)(a).Set("extends1", extends1)
}

func (a *RoomDef) GetExtends2() *KVStrInt32 {
	return (*attr.StrMap)(a).Value("extends2").(*KVStrInt32)
}
func (a *RoomDef) SetExtends2(extends2 *KVStrInt32) {
	extends2.setParent("extends2", (*attr.StrMap)(a))
	(*attr.StrMap)(a).Set("extends2", extends2)
}

func (a *RoomDef) GetExtends3() *KVStrStr {
	return (*attr.StrMap)(a).Value("extends3").(*KVStrStr)
}
func (a *RoomDef) SetExtends3(extends3 *KVStrStr) {
	extends3.setParent("extends3", (*attr.StrMap)(a))
	(*attr.StrMap)(a).Set("extends3", extends3)
}

func (a *RoomDef) GetDesk111() *DeskDef {
	return (*attr.StrMap)(a).Value("desk888").(*DeskDef)
}
func (a *RoomDef) SetDesk111(desk888 *DeskDef) {
	desk888.setParent("desk888", (*attr.StrMap)(a))
	(*attr.StrMap)(a).Set("desk888", desk888)
}

func (a *RoomDef) GetDesks222() *KVInt32DeskDef {
	return (*attr.StrMap)(a).Value("desks999").(*KVInt32DeskDef)
}
func (a *RoomDef) SetDesks222(desks999 *KVInt32DeskDef) {
	desks999.setParent("desks999", (*attr.StrMap)(a))
	(*attr.StrMap)(a).Set("desks999", desks999)
}

func (a *RoomDef) GetDesks333() *KVStrDeskDef {
	return (*attr.StrMap)(a).Value("desks321").(*KVStrDeskDef)
}
func (a *RoomDef) SetDesks333(desks321 *KVStrDeskDef) {
	desks321.setParent("desks321", (*attr.StrMap)(a))
	(*attr.StrMap)(a).Set("desks321", desks321)
}

func (a *RoomDef) GetDesksArr() *DeskDefSlice {
	return (*attr.StrMap)(a).Value("desks").(*DeskDefSlice)
}
func (a *RoomDef) SetDesksArr(desks *DeskDefSlice) {
	desks.setParent("desks", (*attr.StrMap)(a))
	(*attr.StrMap)(a).Set("desks", desks)
}

func (a *RoomDef) GetInt8ss() *Int8Slice {
	return (*attr.StrMap)(a).Value("int8ss").(*Int8Slice)
}
func (a *RoomDef) SetInt8ss(int8ss *Int8Slice) {
	int8ss.setParent("int8ss", (*attr.StrMap)(a))
	(*attr.StrMap)(a).Set("int8ss", int8ss)
}

func (a *RoomDef) HasChange() bool {
	return (*attr.StrMap)(a).HasChange()
}
func (a *RoomDef) ChangeKey() map[string]struct{} {
	return (*attr.StrMap)(a).ChangeKey()
}
func (a *RoomDef) ClearChangeKey() {
	(*attr.StrMap)(a).ClearChangeKey()
}
func (a *RoomDef) setParent(k string, parent attr.Field) {
	(*attr.StrMap)(a).SetParent(k, parent)
}
func (a *RoomDef) ForEach(fn func(k string, v interface{}) bool) {
	(*attr.StrMap)(a).ForEach(fn)
}
func (a *RoomDef) Equal(other *RoomDef) bool {
	return (*attr.StrMap)(a).Equal((*attr.StrMap)(other))
}
func (a *RoomDef) data() map[string]interface{} {
	dd := map[string]interface{}{}
	a.ForEach(func(k string, v interface{}) bool {
		dd[k] = v
		return true
	})
	return dd
}
func (a *RoomDef) MarshalJSON() ([]byte, error) {
	return json.Marshal((*attr.StrMap)(a).ToMap())
}
func (a *RoomDef) UnmarshalJSON(b []byte) error {
	mm, err := roomMeta.UnmarshalJson(b)
	if err != nil {
		return err
	}
	(*attr.StrMap)(a).SetData(mm)
	(*attr.StrMap)(a).ForEach(func(k string, v interface{}) bool {
		if k != "id" && !roomMeta.GetDef(k).IsPrimary() {
			v.(IField).setParent(k, (*attr.StrMap)(a))
		}
		return true
	})
	return nil
}
func (a *RoomDef) MarshalBSON() ([]byte, error) {
	return bson.Marshal((*attr.StrMap)(a).ToMap())
}
func (a *RoomDef) UnmarshalBSON(b []byte) error {
	mm, err := roomMeta.UnmarshalBson(b)
	if err != nil {
		return err
	}
	(*attr.StrMap)(a).SetData(mm)
	(*attr.StrMap)(a).ForEach(func(k string, v interface{}) bool {
		if k != "id" && !roomMeta.GetDef(k).IsPrimary() {
			v.(IField).setParent(k, (*attr.StrMap)(a))
		}
		return true
	})
	return nil
}
